### ISSUE TITLE
Add source / more info to readme

### ISSUE THREAD

**Issue by jtagcat** [vroudge/jest-fuck#2]
Is audible jest-fuck somehow famous or..?
> Searches GH for Audible, sort by stars
> This

**Comment by vroudge** [comment]
I don't think so. I'm just a loner guy from some random country that created this package for the lulz when I was bored. 🤷‍♂️ 

What do you think is missing on the README?

**Comment by jtagcat** [comment]
Why does this have 42 stars, when it's just a seemingly random fuck.wav.

**Comment by vroudge** [comment]
I don't know. One could say it's funny to play a loud `fuck` when your tests fail.

**Comment by jtagcat** [comment]
_just realized Audible isn't only audiobooks, it's also audible_

**Comment by vroudge** [comment]
https://www.dictionary.com/browse/audible

_audible: (adj) capable of being heard; loud enough to be heard; actually heard._

Are you ok D:

**Comment by jtagcat** [comment]
Yes, I was just ctrl+f-ing everything audible, didn't realize at the moment that audible means a word as well...

Brain: Audible, fuck, the 'this is audible' guy going fuck? No it isn't. Hmm. New issue.

Now it's just ack failure and hide :upside_down_face:
